services:
  urban:
    container_name: urban
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped

networks:
  default:
    external: true
    name: krokosik-web-services